#!/usr/bin/env python
"""Implement the ``codemap-py integrate`` cross-runtime integration boundary.

Purpose:
    Provide one adapter-free CLI for read-only integration audits and separately approved
    source/runtime mutations. Either host can select Claude, Codex, or both without importing
    the other host or a consumer package.
Scope:
    The closed consumer set is Claude ``foundry``, ``oss``, ``develop``, ``research`` and Codex
    ``codex-rig``; the provider is ``codemap-py``. Unknown consumers are refused, never
    discovered. ``audit`` reads bounded local evidence only; ``plan``, ``apply``, and ``sync``
    retain distinct state ownership.
Usage:
    The CLI entrypoint calls :func:`run` with arguments after ``integrate``. Use ``audit`` to
    inspect state, then explicitly create and approve a plan before ``apply`` or ``sync``.
Outputs:
    ``audit --json`` emits schema-versioned evidence. Mutation modes emit plans, journals, and
    bounded JSON results under task-specific ``.reports/integrate/`` directories.
Failure:
    Usage errors exit ``2``. Contract violations and required mutation failures exit ``1``.
    :func:`run` emits bounded JSON errors instead of tracebacks at the CLI boundary.
Used by:
    ``codemap_py.cli``, the Claude and Codex integration skills, and focused integration tests.
"""

# The pre-split ``integration.py`` exposed its own module-level imports as attributes,
# and in-tree callers read or patch through them. Re-exported here so the package keeps
# the same attribute surface as the module it replaces.
import argparse  # noqa: F401
import contextlib  # noqa: F401
import hashlib  # noqa: F401
import json  # noqa: F401
import os  # noqa: F401
import re  # noqa: F401
import shutil  # noqa: F401
import subprocess  # noqa: F401
import sys  # noqa: F401
import tempfile  # noqa: F401
import time  # noqa: F401
import uuid  # noqa: F401
from collections.abc import Callable, Mapping, Sequence  # noqa: F401
from dataclasses import dataclass  # noqa: F401
from datetime import date, datetime, timezone  # noqa: F401
from enum import Enum  # noqa: F401
from io import StringIO  # noqa: F401
from pathlib import Path  # noqa: F401

from codemap_py import __version__, index_paths, query, runtime_log, rwgate, scanner  # noqa: F401

from .apply_sync import (
    Journal,
    _apply_one,
    _atomic_write,
    _classify_mutation,
    _git_dirty,
    _handle_apply_failure,
    _handle_sync_failure,
    _is_contained,
    _is_installed_cache_path,
    _recovery_commands_source,
    _recovery_commands_sync,
    _refuse_if,
    _refuse_unverified_identity,
    _rollback_runtime_sync,
    _rollback_source_writes,
    _sync_one,
    _validate_runtime_sync,
    _validate_source_write,
    _verify_plugin_installed,
    apply_plan,
    cmd_apply,
    cmd_sync,
    load_plan,
    sync_plan,
    verify_approval,
)
from .audit import (
    _CLAUDE_SELECTORS,
    _CODEX_SELECTORS,
    _MAX_AUDIT_DEGRADED_MODULES,
    _MAX_AUDIT_INDEX_BYTES,
    _MAX_AUDIT_LOG_FILES,
    _MAX_AUDIT_LOG_RECORDS,
    _audit_finding,
    _audit_flat_logs,
    _audit_index_evidence,
    _audit_remediation,
    _audit_runtime_logs,
    _audit_state_findings,
    _audit_status,
    _complete_query_module,
    _consumer_audit,
    _parse_audit_timestamp,
    _print_audit_text,
    _query_guidance_evidence,
    _query_guidance_findings,
    _read_audit_records,
    _record_index_path,
    _record_is_in_window,
    _runtime_audit,
    _target_names_module,
    _usage_avoidance_by_runtime,
    _usage_findings,
    _usage_session_evidence,
    _usage_summary,
    build_audit_report,
    cmd_audit,
)
from .cli import (
    _COMMANDS,
    _add_apply_parser,
    _add_audit_parser,
    _add_demo_parser,
    _add_plan_parser,
    _add_runtime_flag,
    _add_sync_parser,
    _build_parser,
    _emit_bounded_error,
    _parse_since,
    _split_csv,
    run,
)
from .demo import (
    _demo_query,
    cmd_demo,
    run_demo,
)
from .managed_block import (
    _CODEX_RIG_AGENTS_BEGIN_RE,
    _CODEX_RIG_AGENTS_END,
    _MANAGED_BEGIN_RE,
    _MANAGED_END,
    BLOCK_SCHEMA_VERSION,
    PROTOCOL_VERSION,
    _managed_block_body,
    _managed_block_status,
    _managed_protocol,
    _mutate_content,
    _render_managed_block,
    _replace_managed_region,
)
from .native import (
    _IDENTITY_READ_CHUNK_BYTES,
    _MAX_PROVIDER_IDENTITY_BYTES,
    _MAX_PROVIDER_IDENTITY_FILES,
    _NATIVE_TIMEOUT_S,
    _PROVIDER_IDENTITY_DIRS,
    _PROVIDER_IDENTITY_DOCS,
    _PROVIDER_IDENTITY_EXCLUDED_PARTS,
    _WINDOWS_BATCH_METACHARACTERS,
    _claude_installed_version,
    _codex_home,
    _codex_installed_version,
    _installed_version_lookup,
    _marketplace_entry,
    _native_json_probe,
    _native_plugin_record,
    _provider_content_identity,
    _resolve_native_command,
    _run_native,
    _run_native_required,
    _unsafe_windows_batch_argv,
    codex_rig_global_status,
)
from .plan import (
    _marketplace_source,
    _marketplace_sync_op,
    _plugin_sync_op,
    _runtime_sync_ops,
    _source_write_op,
    build_plan,
    cmd_plan,
)
from .types import (
    _EXIT_OK,
    _EXIT_RUNTIME,
    _EXIT_USAGE,
    ALL_TARGETS,
    CLAUDE_TARGETS,
    CODEX_TARGETS,
    CONSUMER_MANAGED_FILE,
    MARKETPLACE_NAME,
    MARKETPLACE_REMOTE,
    PROVIDER_DIR,
    PROVIDER_NAME,
    SCHEMA_VERSION,
    ApprovalError,
    ConsumerTarget,
    IntegrationError,
    RefusalError,
    Runtime,
    Source,
    _cli_for,
    _find_target,
    _runtimes_of,
    _targets_for_runtime,
    resolve_targets,
)
from .util import (
    _GIT_TIMEOUT_S,
    _MAX_JSON_BYTES,
    _SHA256_RE,
    _canonical_json,
    _manifest_for,
    _read_json_file,
    _report_dir,
    _sha256_bytes,
    _sha256_file,
    _utc_now_iso,
    _utc_stamp,
    compute_plan_sha256,
)

__all__ = [
    "ALL_TARGETS",
    "BLOCK_SCHEMA_VERSION",
    "CLAUDE_TARGETS",
    "CODEX_TARGETS",
    "CONSUMER_MANAGED_FILE",
    "MARKETPLACE_NAME",
    "MARKETPLACE_REMOTE",
    "PROTOCOL_VERSION",
    "PROVIDER_DIR",
    "PROVIDER_NAME",
    "SCHEMA_VERSION",
    "_CLAUDE_SELECTORS",
    "_CODEX_RIG_AGENTS_BEGIN_RE",
    "_CODEX_RIG_AGENTS_END",
    "_CODEX_SELECTORS",
    "_COMMANDS",
    "_EXIT_OK",
    "_EXIT_RUNTIME",
    "_EXIT_USAGE",
    "_GIT_TIMEOUT_S",
    "_IDENTITY_READ_CHUNK_BYTES",
    "_MANAGED_BEGIN_RE",
    "_MANAGED_END",
    "_MAX_AUDIT_DEGRADED_MODULES",
    "_MAX_AUDIT_INDEX_BYTES",
    "_MAX_AUDIT_LOG_FILES",
    "_MAX_AUDIT_LOG_RECORDS",
    "_MAX_JSON_BYTES",
    "_MAX_PROVIDER_IDENTITY_BYTES",
    "_MAX_PROVIDER_IDENTITY_FILES",
    "_NATIVE_TIMEOUT_S",
    "_PROVIDER_IDENTITY_DIRS",
    "_PROVIDER_IDENTITY_DOCS",
    "_PROVIDER_IDENTITY_EXCLUDED_PARTS",
    "_SHA256_RE",
    "_WINDOWS_BATCH_METACHARACTERS",
    "ApprovalError",
    "ConsumerTarget",
    "IntegrationError",
    "Journal",
    "RefusalError",
    "Runtime",
    "Source",
    "_add_apply_parser",
    "_add_audit_parser",
    "_add_demo_parser",
    "_add_plan_parser",
    "_add_runtime_flag",
    "_add_sync_parser",
    "_apply_one",
    "_atomic_write",
    "_audit_finding",
    "_audit_flat_logs",
    "_audit_index_evidence",
    "_audit_remediation",
    "_audit_runtime_logs",
    "_audit_state_findings",
    "_audit_status",
    "_build_parser",
    "_canonical_json",
    "_classify_mutation",
    "_claude_installed_version",
    "_cli_for",
    "_codex_home",
    "_codex_installed_version",
    "_complete_query_module",
    "_consumer_audit",
    "_demo_query",
    "_emit_bounded_error",
    "_find_target",
    "_git_dirty",
    "_handle_apply_failure",
    "_handle_sync_failure",
    "_installed_version_lookup",
    "_is_contained",
    "_is_installed_cache_path",
    "_managed_block_body",
    "_managed_block_status",
    "_managed_protocol",
    "_manifest_for",
    "_marketplace_entry",
    "_marketplace_source",
    "_marketplace_sync_op",
    "_mutate_content",
    "_native_json_probe",
    "_native_plugin_record",
    "_parse_audit_timestamp",
    "_parse_since",
    "_plugin_sync_op",
    "_print_audit_text",
    "_provider_content_identity",
    "_query_guidance_evidence",
    "_query_guidance_findings",
    "_read_audit_records",
    "_read_json_file",
    "_record_index_path",
    "_record_is_in_window",
    "_recovery_commands_source",
    "_recovery_commands_sync",
    "_refuse_if",
    "_refuse_unverified_identity",
    "_render_managed_block",
    "_replace_managed_region",
    "_report_dir",
    "_resolve_native_command",
    "_rollback_runtime_sync",
    "_rollback_source_writes",
    "_run_native",
    "_run_native_required",
    "_runtime_audit",
    "_runtime_sync_ops",
    "_runtimes_of",
    "_sha256_bytes",
    "_sha256_file",
    "_source_write_op",
    "_split_csv",
    "_sync_one",
    "_target_names_module",
    "_targets_for_runtime",
    "_unsafe_windows_batch_argv",
    "_usage_avoidance_by_runtime",
    "_usage_findings",
    "_usage_session_evidence",
    "_usage_summary",
    "_utc_now_iso",
    "_utc_stamp",
    "_validate_runtime_sync",
    "_validate_source_write",
    "_verify_plugin_installed",
    "apply_plan",
    "build_audit_report",
    "build_plan",
    "cmd_apply",
    "cmd_audit",
    "cmd_demo",
    "cmd_plan",
    "cmd_sync",
    "codex_rig_global_status",
    "compute_plan_sha256",
    "load_plan",
    "resolve_targets",
    "run",
    "run_demo",
    "sync_plan",
    "verify_approval",
]
