"""Acceptance checks for deterministic plugin package generation."""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from types import ModuleType, SimpleNamespace

import pytest

from _platform import FILE_SYMLINKS_AVAILABLE, POSIX_FILE_MODES_AVAILABLE

_requires_posix_file_modes = pytest.mark.skipif(
    not POSIX_FILE_MODES_AVAILABLE, reason="filesystem does not preserve POSIX file modes"
)
_requires_file_symlinks = pytest.mark.skipif(
    not FILE_SYMLINKS_AVAILABLE, reason="filesystem cannot create file symlinks"
)
PLUGIN_ROOT = Path(__file__).resolve().parents[1]
BUILD_SCRIPT = PLUGIN_ROOT / "scripts" / "build_package.py"


def _load_builder(path: Path = BUILD_SCRIPT) -> ModuleType:
    """Load one package builder directly from its file path."""
    specification = importlib.util.spec_from_file_location("codex_rig_build_package", path)
    assert specification is not None
    assert specification.loader is not None
    module = importlib.util.module_from_spec(specification)
    specification.loader.exec_module(module)
    return module


def _run_builder(plugin_root: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    """Run an isolated package builder with bytecode writes disabled."""
    return subprocess.run(
        [sys.executable, str(plugin_root / "scripts" / "build_package.py"), *arguments],
        check=False,
        capture_output=True,
        text=True,
        env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
    )


def _copied_plugin(tmp_path: Path) -> Path:
    """Copy only installed-package bytes into a source-independent fixture."""
    destination = tmp_path / "installed-plugin"
    shutil.copytree(
        PLUGIN_ROOT,
        destination,
        ignore=shutil.ignore_patterns("__pycache__", ".pytest_cache", ".coverage"),
    )
    assert not (tmp_path / ".codex").exists()
    return destination


@_requires_posix_file_modes
@pytest.mark.packaging
def test_generation_is_deterministic_and_current() -> None:
    """Prevent nondeterministic fields or a stale committed package manifest."""
    builder = _load_builder()

    first = builder.encode_manifest(builder.build_manifest())
    second = builder.encode_manifest(builder.build_manifest())

    assert first == second == (PLUGIN_ROOT / "package-manifest.json").read_bytes()
    assert b"/Users/" not in first
    assert b"/home/" not in first


@pytest.mark.packaging
def test_manifest_encoding_matches_pre_commit_json_order() -> None:
    """Keep generated bytes stable after the repository JSON formatter runs."""
    builder = _load_builder()
    manifest = builder.build_manifest()

    expected = (json.dumps(manifest, indent=2, ensure_ascii=True, sort_keys=True) + "\n").encode()

    assert builder.encode_manifest(manifest) == expected


@pytest.mark.packaging
def test_portable_manifest_comparison_ignores_only_mode_values() -> None:
    """Let native Windows check release bytes without rewriting POSIX modes."""
    builder = _load_builder()
    current = {
        "schema": 1,
        "files": [{"path": "payload.txt", "sha256": "a" * 64, "mode": "0644"}],
    }
    generated = {
        "schema": 1,
        "files": [{"path": "payload.txt", "sha256": "a" * 64, "mode": "0666"}],
    }

    assert builder.manifests_match(current, generated, enforce_modes=False)
    assert not builder.manifests_match(current, generated, enforce_modes=True)

    generated["files"][0]["sha256"] = "b" * 64
    assert not builder.manifests_match(current, generated, enforce_modes=False)


@pytest.mark.packaging
def test_update_refuses_without_posix_mode_enforcement(monkeypatch: pytest.MonkeyPatch) -> None:
    """Keep authoritative release-mode generation off native Windows."""
    builder = _load_builder()
    monkeypatch.setattr(builder, "parse_args", lambda: SimpleNamespace(check=False, update=True))
    monkeypatch.setattr(builder, "enforces_posix_modes", lambda: False)
    monkeypatch.setattr(builder, "build_manifest", lambda: pytest.fail("update continued into generation"))

    with pytest.raises(SystemExit, match="package-manifest-update-requires-posix"):
        builder.main()


@pytest.mark.packaging
def test_check_uses_verified_manifest_without_posix_mode_enforcement(
    capsys: pytest.CaptureFixture[str], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Keep native Windows checks bound to verified installed-package bytes."""
    builder = _load_builder()
    calls: list[tuple[Path, bool]] = []
    monkeypatch.setattr(builder, "parse_args", lambda: SimpleNamespace(check=True, update=False))
    monkeypatch.setattr(builder, "enforces_posix_modes", lambda: False)
    monkeypatch.setattr(
        builder,
        "verify_package",
        lambda root, *, enforce_modes: calls.append((root, enforce_modes)),
    )
    monkeypatch.setattr(builder, "build_manifest", lambda: pytest.fail("native Windows regenerated the manifest"))

    builder.main()

    assert calls == [(builder.PACKAGE_ROOT, False)]
    assert capsys.readouterr().out == "Package manifest is current.\n"


@_requires_posix_file_modes
@pytest.mark.packaging
def test_manifest_binds_the_pure_role_generator() -> None:
    """Prevent installed managers from importing unbound generator bytes."""
    builder = _load_builder()
    manifest = builder.build_manifest()
    generator = PLUGIN_ROOT / "scripts" / "generate_roles.py"

    assert manifest["generator"] == {
        "version": 1,
        "path": "scripts/generate_roles.py",
        "sha256": builder.sha256(generator.read_bytes()),
    }
    record = next(item for item in manifest["files"] if item["path"] == "scripts/generate_roles.py")
    assert record == {
        "path": "scripts/generate_roles.py",
        "sha256": manifest["generator"]["sha256"],
        "mode": "0644",
    }


@_requires_posix_file_modes
@pytest.mark.packaging
def test_generation_checks_source_independent_installed_copy(tmp_path: Path) -> None:
    """Prove manifest validation does not require the repository source tree."""
    installed = _copied_plugin(tmp_path)

    result = _run_builder(installed, "--check")

    assert result.returncode == 0, result.stderr
    assert result.stdout == "Package manifest is current.\n"


@_requires_posix_file_modes
@pytest.mark.packaging
def test_update_rewrites_stale_manifest(tmp_path: Path) -> None:
    """Prevent the explicit update mode from leaving stale package hashes."""
    installed = _copied_plugin(tmp_path)
    role = installed / "roles" / "challenger" / "ROLE.md"
    role.write_text(role.read_text(encoding="utf-8") + "\n", encoding="utf-8")

    stale = _run_builder(installed, "--check")
    updated = _run_builder(installed, "--update")
    current = _run_builder(installed, "--check")

    assert stale.returncode != 0
    assert updated.returncode == 0, updated.stderr
    assert updated.stdout == "Updated package manifest: package-manifest.json\n"
    assert current.returncode == 0, current.stderr


@_requires_posix_file_modes
@pytest.mark.packaging
def test_update_is_idempotent_after_normalizing_stale_manifest(tmp_path: Path) -> None:
    """Prevent platform normalization from causing repeated manifest rewrites."""
    installed = _copied_plugin(tmp_path)
    manifest = installed / "package-manifest.json"
    original = manifest.read_bytes()
    stale = original.replace(b'"mode": "0644"', b'"mode": "0000"', 1)
    assert stale != original
    manifest.write_bytes(stale)

    prepared = _run_builder(installed, "--update")
    assert prepared.returncode == 0, prepared.stderr
    assert prepared.stdout == "Updated package manifest: package-manifest.json\n"
    before = manifest.stat().st_mtime_ns

    result = _run_builder(installed, "--update")

    assert result.returncode == 0, result.stderr
    assert result.stdout == "Package manifest is current.\n"
    assert manifest.stat().st_mtime_ns == before


@pytest.mark.parametrize(
    ("mutator", "expected"),
    [
        pytest.param(
            lambda root: (root / "roles" / "challenger" / "ROLE.md").unlink(),
            "missing canonical role card",
            id="missing-role",
        ),
        pytest.param(
            lambda root: (root / "skills" / "assess" / "SKILL.md").unlink(),
            "missing workflow skill",
            id="missing-skill",
        ),
    ],
)
@pytest.mark.packaging
def test_generation_rejects_incomplete_public_roster(
    tmp_path: Path, mutator: Callable[[Path], None], expected: str
) -> None:
    """Reject an incomplete installed roster on every supported platform."""
    installed = _copied_plugin(tmp_path)
    mutator(installed)
    builder = _load_builder(installed / "scripts" / "build_package.py")

    with pytest.raises(ValueError, match=expected):
        builder.build_manifest()


@pytest.mark.packaging
def test_generation_excludes_runtime_report_debris(tmp_path: Path) -> None:
    """Runtime `.reports/` artifacts never enter or invalidate the package manifest.

    A calibration run writes gitignored, machine-local artifacts under `.reports/` inside the plugin tree; a later
    manifest refresh must neither sweep those paths into the tracked manifest nor report the manifest stale because of
    them.
    """
    installed = _copied_plugin(tmp_path)
    debris = installed / ".reports" / "codex" / "calibration" / "run" / "debris.txt"
    debris.parent.mkdir(parents=True)
    debris.write_text("machine-local runtime artifact\n", encoding="utf-8")

    result = _run_builder(installed, "--check")

    assert result.returncode == 0, result.stderr
    assert result.stdout == "Package manifest is current.\n"


@_requires_posix_file_modes
@_requires_file_symlinks
@pytest.mark.packaging
def test_generation_rejects_symlinked_payload(tmp_path: Path) -> None:
    """Prevent a generated manifest from blessing a payload symlink."""
    installed = _copied_plugin(tmp_path)
    target = installed / "roles" / "challenger" / "ROLE.md"
    target.unlink()
    target.symlink_to(installed / "roles" / "curator" / "ROLE.md")

    result = _run_builder(installed, "--update")

    assert result.returncode == 2
    assert "symlink payload forbidden" in result.stderr
